image: golang:1.11

stages:
  - test
  - build
  - integration_test

variables:
  GOCACHE: $CI_PROJECT_DIR/.gobuild
  GOPATH: $CI_PROJECT_DIR/.gotree
  PKG_DIR: $CI_PROJECT_DIR/.gotree/src/github.com/onederx
  PKG: $CI_PROJECT_DIR/.gotree/src/github.com/onederx/bitcoin-processing
  GO111MODULE: "on"

cache:
  paths:
    - .gobuild/
    - .gotree/

before_script:
  - mkdir -p $PKG_DIR
  - ln -s $CI_PROJECT_DIR $PKG
  - cd $PKG
  - go get -v -d ./...

after_script:
    - rm $PKG


build:
  stage: build
  script:
    - (cd cmd/bitcoin-processing && go build)
    - (cd cmd/bitcoin-processing-client && go build)
    - go test -tags integration -o integrationtests/integration.test -c ./integrationtests
  artifacts:
    paths:
      - cmd/bitcoin-processing/bitcoin-processing
      - cmd/bitcoin-processing-client/bitcoin-processing-client
      - integrationtests/integration.test


unit_tests:
  stage: test
  script:
    - cd $PKG
    - go test -v ./...


integration_test:
  tags:
    - integration-tests
  stage: integration_test
  before_script: &integration_test_docker_cleanup
    - export TSTPREFIX='bitcoin-processing-integration-test'
    - docker stop ${TSTPREFIX}-db || true && docker rm ${TSTPREFIX}-db || true
    - docker stop ${TSTPREFIX}-node-our || true && docker rm ${TSTPREFIX}-node-our || true
    - docker stop ${TSTPREFIX}-node-client || true && docker rm ${TSTPREFIX}-node-client || true
    - docker stop ${TSTPREFIX}-node-miner || true && docker rm ${TSTPREFIX}-node-miner || true
    - docker stop ${TSTPREFIX}-main || true && docker rm ${TSTPREFIX}-main || true
  after_script: *integration_test_docker_cleanup
  script:
    - docker pull kylemanna/bitcoind && docker pull debian:stretch && docker pull postgres:10.5
    - (cd integrationtests && ./integration.test -test.v -test.timeout=20m )
  artifacts:
    paths:
      - integrationtests/*.log
    when: on_failure
