image: golang:1.11

stages:
  - test
  - build

variables:
  GOCACHE: $CI_PROJECT_DIR/.gobuild
  GOPATH: $CI_PROJECT_DIR/.gotree
  PKG_DIR: $CI_PROJECT_DIR/.gotree/src/github.com/onederx
  PKG: $CI_PROJECT_DIR/.gotree/src/github.com/onederx/bitcoin-processing

cache:
  paths:
    - .gobuild/
    - .gotree/

before_script:
  - mkdir -p $PKG_DIR
  - ln -s $CI_PROJECT_DIR $PKG
  - cd $PKG
  - go get -v -d ./...

after_script:
    - rm $PKG


build:
  stage: build
  script:
    - (cd cmd/bitcoin-processing && go build)
    - (cd cmd/bitcoin-processing-client && go build)
  artifacts:
    paths:
      - cmd/bitcoin-processing/bitcoin-processing
      - cmd/bitcoin-processing-client/bitcoin-processing-client


unit_tests:
  stage: test
  script:
    - cd $PKG
    - go test ./...